[package]
name = "crab-toolchain"
version = "0.1.0"
authors = ["pintera"]
edition = "2018"
license = "MIT"

[[bin]]
path = "src/main.rs"
name = "crab"

[dependencies.nom]
version = "6.1.0"

[dev-dependencies.indoc]
version = "1.0.3"
